image: "hub.ricebook.net/base/centos:onbuild-eru-agent-2017.07.27"
stages:
  - test
  - build
  - deploy
test:
  stage: test
  tags:
    - docker
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - "make test"
build:
  stage: build
  tags:
    - docker
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - "make build"
    - "cp -r agent $CI_PROJECT_DIR"
  artifacts:
    paths:
      - "agent"
    expire_in: 1 week
dockerized_agent:
  stage: deploy
  tags:
    - shell
  script:
    - VERSION=`./agent -v | sed -e 's/Eru-Agent\ version\ //'`
    - IMAGENAME=hub.ricebook.net/eru/agent:${VERSION}
    - "docker build --no-cache -t $IMAGENAME ."
    - "docker push $IMAGENAME"
    - "docker rmi $IMAGENAME"
  dependencies:
    - "build"
rpm:
  stage: deploy
  tags:
    - docker
  script:
    - "./make-rpm"
  dependencies:
    - "build"
  artifacts:
    paths:
      - "eru-agent*.rpm"
    expire_in: 1 week

