image: "hub.ricebook.net/base/centos:eru-agent-onbuild-2016.09.01"
stages:
  - build
  - rpm
build:
  stage: build
  script:
    - "echo 'start building'"
    - "ln -s $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - go build -ldflags "-s -w" -a -tags netgo -installsuffix netgo
    - "echo 'build done'"
  artifacts:
    paths:
      - "agent"
    expire_in: 1 week
rpm:
  stage: rpm
  script:
    - "echo 'start make rpm'"
    - "./make-rpm"
    - "echo 'make rpm done'"
  dependencies:
    - "build"
  artifacts:
    paths:
      - "eru-agent*.rpm"
    expire_in: 1 week

