image: "hub.ricebook.net/base/centos:onbuild-eru-agent-2017.04.21"
stages:
  - test
  - build
  - dockerized
test:
  stage: test
  tags:
    - docker
  script:
    - "ln -s $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - "make test"
build:
  stage: build
  tags:
    - docker
  script:
    - "ln -s $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - "make build"
  artifacts:
    paths:
      - "agent"
    expire_in: 1 week
dockerized_agent:
  stage: dockerized
  tags:
    - shell
  script:
    - COMMIT=`git rev-parse HEAD | head -c 7`
    - IMAGENAME=hub.ricebook.net/platform/eruagent:${COMMIT}
    - "docker build --no-cache -t $IMAGENAME ."
    - "docker push $IMAGENAME"
    - "docker rmi $IMAGENAME"
  dependencies:
    - "build"