image: "hub.ricebook.net/base/centos:onbuild-eru-agent-2017.02.07"
stages:
  - build
  - rpm
build:
  stage: build
  script:
    - "ln -s $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/agent"
    - go build -ldflags "-s -w" -a -tags netgo -installsuffix netgo
  artifacts:
    paths:
      - "agent"
    expire_in: 1 week
rpm:
  stage: rpm
  script:
    - "./make-rpm"
  dependencies:
    - "build"
  artifacts:
    paths:
      - "eru-agent*.rpm"
    expire_in: 1 week

